### ISSUE TITLE
AGEPRO description fix on "Fish and Fisheries Tools" page

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-fish-tools/AGEPRO#4]
Current AGEPRO description the Fish and Fisheries Tools page:
(https://nmfs-fish-tools.github.io/)

![Screenshot 2021-07-09 082406](https://user-images.githubusercontent.com/37851243/125121127-27f14300-e08f-11eb-83b8-2fa1a461c151.png)

Originally: 
Stock Assessment Model
Age-structured model

**Comment by ChristineStawitz-NOAA** [comment]
I have changed this to "Stock Assessment Model" and "Statistical Catch-at-Age" but let me know if this is inaccurate
